# action.yml
name: 'PR CHECK'
description: 'Checa se hรก PR abertos em outros branches'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_CONTEXT: ${{ toJson(github) }}
  run: |
    echo "$GITHUB_CONTEXT"
    echo ${{ github.event.pull_request.title }}
  
    
